#!/bin/bash
# 直接修复脚本

HOST="10.66.66.3"
USERNAME="root"
PASSWORD="${DEPLOY_SSH_PASSWORD:?请先 export DEPLOY_SSH_PASSWORD=你的root密码}"
REMOTE_DIR="/opt/ai-novel-agent"

echo "直接修复脚本"
echo "================"

# 使用expect自动登录并执行
expect << EOF
spawn ssh $USERNAME@$HOST
expect "password:"
send "$PASSWORD\r"
expect "#"

# 停止服务
send "systemctl stop ai-novel-agent 2>/dev/null || true\r"
expect "#"
send "pkill -f 'uvicorn app.main:app' 2>/dev/null || true\r"
expect "#"
send "sleep 2\r"
expect "#"

# 修复Agent文件
send "cd $REMOTE_DIR\r"
expect "#"

# 修复每个Agent文件
send "for agent in trend style planner reviser scorer; do\r"
expect "#"
send "  if [ -f 'backend/app/agents/\$agent.py' ]; then\r"
expect "#"
send "    echo '修复: \$agent.py'\r"
expect "#"
send "    # 检查是否已有__init__\r"
expect "#"
send "    if ! grep -q 'def __init__(self, task_id):' 'backend/app/agents/\$agent.py'; then\r"
expect "#"
send "      sed -i '/class.*Agent.*:/a\\\\    def __init__(self, task_id):\\\\        super().__init__(task_id)' 'backend/app/agents/\$agent.py'\r"
expect "#"
send "    fi\r"
expect "#"
send "  fi\r"
expect "#"
send "done\r"
expect "#"

# 验证修复
send "python3 -c '\r"
send "import sys\r"
send "sys.path.insert(0, \"backend/app\")\r"
send "\r"
send "agents = [\"TrendAgent\", \"StyleAgent\", \"PlannerAgent\", \"ReviserAgent\", \"ScorerAgent\"]\r"
send "all_ok = True\r"
send "\r"
send "for agent_name in agents:\r"
send "  try:\r"
send "    module_name = agent_name.lower().replace(\"agent\", \"\")\r"
send "    exec(f\"from agents.{module_name} import {agent_name}\")\r"
send "    agent_class = eval(agent_name)\r"
send "    agent = agent_class(\"test_123\")\r"
send "    print(f\"[OK] {agent_name}: 创建成功\")\r"
send "  except Exception as e:\r"
send "    print(f\"[ERROR] {agent_name}: {e}\")\r"
send "    all_ok = False\r"
send "\r"
send "if all_ok:\r"
send "  print(\"所有Agent修复成功\")\r"
send "else:\r"
send "  print(\"有Agent修复失败\")\r"
send "'\r"
expect "#"

# 启动服务
send "systemctl start ai-novel-agent\r"
expect "#"
send "sleep 5\r"
expect "#"

# 检查状态
send "systemctl status ai-novel-agent --no-pager | head -8\r"
expect "#"

# 简单测试
send "python3 -c '\r"
send "import requests\r"
send "import time\r"
send "\r"
send "print(\"简单测试...\")\r"
send "\r"
send "# 创建任务\r"
send "resp = requests.post(\r"
send "  \"http://localhost:9000/api/tasks\",\r"
send "  json={\"name\": \"直接修复测试\", \"chapter_count\": 1},\r"
send "  timeout=10\r"
send ")\r"
send "\r"
send "if resp.status_code == 200:\r"
send "  task_id = resp.json().get(\"task_id\")\r"
send "  print(f\"任务创建成功: {task_id}\")\r"
send "  \r"
send "  # 启动\r"
send "  start_resp = requests.post(\r"
send "    f\"http://localhost:9000/api/tasks/{task_id}/start\",\r"
send "    timeout=10\r"
send "  )\r"
send "  print(f\"启动: {start_resp.status_code}\")\r"
send "  \r"
send "  # 检查进度\r"
send "  time.sleep(5)\r"
send "  progress_resp = requests.get(\r"
send "    f\"http://localhost:9000/api/tasks/{task_id}/progress\",\r"
send "    timeout=10\r"
send "  )\r"
send "  \r"
send "  if progress_resp.status_code == 200:\r"
send "    progress = progress_resp.json()\r"
send "    print(f\"任务状态: {progress.get('task_status', 'unknown')}\")\r"
send "    \r"
send "    for agent in [\"TrendAgent\", \"StyleAgent\", \"PlannerAgent\"]:\r"
send "      if agent in progress:\r"
send "        status = progress[agent].get(\"status\", \"unknown\")\r"
send "        print(f\"  {agent}: {status}\")\r"
send "  else:\r"
send "    print(f\"获取进度失败: {progress_resp.status_code}\")\r"
send "else:\r"
send "  print(f\"创建失败: {resp.status_code}, {resp.text}\")\r"
send "'\r"
expect "#"

send "exit\r"
expect eof
EOF

echo "修复完成"
echo "请在前端测试: http://10.66.66.3:9000/"